### ISSUE TITLE
Information not saved in forms

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#208]
Pasta version pasta_eln-2.5.0b3

1. Go to any table view (Measurements, Samples, etc.).
2. Create an item by "Add"

Only name and tags will be saved when the item is created, which is an old issue.
Comments will be saved when the item is opened again for editing.

**New issue:**
1.When content is added to the procedure item via editing, it is not saved. 
2. Same for instruments: vendor is not saved when added during item editing. 
3. Samples: chemical structure is not saved when added during item editing. 
4. Measurements: links to samples and procedures are not saved when added during item editing.

**Comment by HTsybenko** [comment]
@SteffenBrinckmann I saw that solving this issue was postponed until 2.6. 

However, it might be rather a critical one and should not get into the next released version.

For clarification, by "metadata being not saved in forms," I don't mean that the previously entered metadata should auto-populate the form when opened for editing again. In fact, the metadata entered via forms does not appear in the corresponding cell of the table upon saving, which may indicate that it is not saved at all.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko It is critical, no doubt. But it is a form-problem and all form-problems are fixed together in 2.6. It is about grouping causes not about grouping priorities.

**Comment by HTsybenko** [comment]
@SteffenBrinckmann It totally makes sense to me. However, I was worrying that the version 2.5 will get a full release with this issue still hanging.

**Comment by HTsybenko** [comment]
The issue also applies to new metadata fields added via data hierarchy editor.

**Comment by HTsybenko** [comment]
Both old and new problems mentioned in this issue were fixed.
