### ISSUE TITLE
Using recipes leads to strange response

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#34]
- In the project view - open any item with an image to edit - right click on the image- select recipe to apply and click-
- After that, the unidentified table view opens instead of staying in the project view. The changed image appears on the right side of the table.

**Comment by SteffenBrinckmann** [comment]
addressed in PR #45

**Comment by jmurugan-fzj** [comment]
@HTsybenko @SteffenBrinckmann When I right click on the image, I could not find "select recipe to apply and click", I see the context menu item there, but not an item with "select recipe to apply and click", did I miss something? I see only the items on the image as in the screenshot below
![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/8af539f1-1448-4514-9dde-ac5e2e893e1d)

I tired "Minimize/Maximize" there but have seen some other issue, this first minimize that image and then when I right click to maximize the minimized image, the menu item completely disappears and the project information is displayed there. I have captured video, which I can share but cannot paste it here, need to see how to share it, Have you observed this issue already?
![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/07dfbde7-2f5a-4eb4-9d9d-8259f9054362)

**Comment by HTsybenko** [comment]
@jmurugan-fzj You have to first open the item with image to edit: when in the project view, double click on it, and a new editing window will appear. 
In this window, right-click on the enlarged window to see "recipe" options (crop the image, etc.).

**Comment by jmurugan-fzj** [comment]
@HTsybenko Hanna, I opened the image, still do not see those options, I can see only two options: "Open folder in window" & "Hide", see the screen shot below, did you still mean something different?
![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/9f8019d5-adf6-4b06-8577-47359956f94f)

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj you might have to update the extractor list: "System"->"Update extractor list" that should give you the context menu..
However: jpegs like the one you selected only have one recipe, by default. Hence, changing is pointless. If  you go to the .png file above, you can change between two.

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann @HTsybenko If this is the case, then I must say that the bug is not ready for verification since the description does not have enough information to reproduce the bug, please add the necessary steps to the description of this bug and also include test data to reproduce the bug and verify it subsequently after the fix is ready!

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj I was able to reproduce the bug and therefore wrote the bug fix.
I would not write a bug fix for something that does not exist.
@HTsybenko good luck for tomorrow

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann I did not mean that you fixed a bug which does not exist at all :)

My point was that the bug is not well defined enough for a third person to do the verification, the test data should be mentioned and also the steps must be be precise..You could reproduce it easily, because you know the system very well :)

**Comment by SteffenBrinckmann** [comment]
Let's talk about this in our inperson meeting next monday

**Comment by SteffenBrinckmann** [comment]
@jmurugan-fzj  and @HTsybenko 
Ok, I repaired the project view and want to write a short how-to / explanation (JM can test it right now on the 'issue_34_debug' branch and HT can test in in the next version)
- open any project that has multiple items in it
- 1-'visibility/minimize project' will minimize to top bar to not clutter the screen; once it is minimized, the menu changes to 'maximize' to display all again
- any item in the tree below: right click to select 'Hide/Show'; now the item is hidden and not shown. This is permanent until you change back. Now we have a hidden subitem.
- 2- "visibility/display hidden subitems" you can display them temporarily (to check, was there something). This menu changes to omit, and you can omit those items in your display
- 3-"visibility/hide entire project" will hide it and will push you to the main project table, where the project is now not present (it is hidden)
- In project table-"More"-"Display hidden items" will display the hidden items. (hidden and show are the opposite values that either a project and subitem can take)
- Click on the hidden project (it has an eye icon at the end of its name)
- Back in the project view, you can now unhide=show the entire project. [please note that the previously hidden subitem remains hidden, as its own hidden status remains hidden)
- 4-"visibility/minimize subitems" will only show the name of the items in the tree, hence less cluttering and easier to move around.
- once these are minimized, they can be maximized. Minimize and maximize can also be done individually for each: right click. The global maximize / minimize are like a big hammer, they unify into that way of display.

If you encounter issues with this tell me.

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Please find my comments below in  for each points in bold italics

@jmurugan-fzj and @HTsybenko
Ok, I repaired the project view and want to write a short how-to / explanation (JM can test it right now on the 'issue_34_debug' branch and HT can test in in the next version)

open any project that has multiple items in it
1-'visibility/minimize project' will minimize to top bar to not clutter the screen; once it is minimized, the menu changes to 'maximize' to display all again

**_This works as expected, the details of the project appears and disappears, but a glitch exists with the menu item displayed (Visibility | Minimize project), whenever you click on the project in sidebar, the menu item changes to "Minimize project" instead of "Minimize project details"_**
![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/15c4697c-1ea0-46dd-9bbb-7abfd00ce91c)
![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/2c66999e-5efe-4ea0-a688-316130dc029f)
![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/10ef3b3a-a6ec-4e6d-97c6-4445d1b32f49)




any item in the tree below: right click to select 'Hide/Show'; now the item is hidden and not shown. This is permanent until you change back. Now we have a hidden subitem.

**_Tried to right click the sub item and clicked "Hide/Show" to toggle the eye icon on them. It works as expected and in between the trials, I noticed that for one of the collapsible subitem, the toggling stopped, but then after selecting the other items in the menu, this glitch was not reproducible anymore_**


2- "visibility/display hidden subitems" you can display them temporarily (to check, was there something). This menu changes to omit, and you can omit those items in your display

**_I have hidden some sub items as said above and then I tried this sub item and it works as expected_**


3-"visibility/hide entire project" will hide it and will push you to the main project table, where the project is now not present (it is hidden)
In project table-"More"-"Display hidden items" will display the hidden items. (hidden and show are the opposite values that either a project and sub-item can take)
Click on the hidden project (it has an eye icon at the end of its name)
Back in the project view, you can now unhide=show the entire project. [please note that the previously hidden subitem remains hidden, as its own hidden status remains hidden)

**_This also works as expected except for one point that when I hide the project, it's removed from the sidebar, is it the expected behavior? When I un-hide the project, this is not displayed immediately in sidebar, if I move the app GUI or resize then it's re-displayed, like a minor glitch, nothing major :)_**
![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/b0090051-ab81-47b3-b904-c24a606380f0)
![image](https://github.com/PASTA-ELN/pasta-eln/assets/141253011/5611d79e-1756-447d-aa30-467889981ca9)


4-"visibility/minimize subitems" will only show the name of the items in the tree, hence less cluttering and easier to move around.
once these are minimized, they can be maximized. Minimize and maximize can also be done individually for each: right click. The global maximize / minimize are like a big hammer, they unify into that way of display.

**_This is also working as expected_**

**Comment by SteffenBrinckmann** [comment]
Thank you for the review. I fixed the 'Minimize project details' glitch.
The sidebar behavior is as (expected): if the project is hidden it is hidden = not shown in sidebar and will only reappear there, if it is unhidden / shown. (I fixed: the sidebar will now display the project immediately when it becomes shown)

**Comment by HTsybenko** [comment]
The issue of opening unidentified table view when using recipes was partially resolved. 
However, after fixing, using recipes leads to opening a project table view, instead of staying in the opened project view and updating the thumbnail of the edited item.

I have added a video to the Sciebo folder that shows how to recreate it.

**Comment by HTsybenko** [comment]
The issue  of opening a table view when using recipes was resolved in the latest version.
