### ISSUE TITLE
Automated re-reordering of items in the project view

### ISSUE THREAD

**Issue by gwinkens** [PASTA-ELN/pasta-eln#389]
1. Before:
![Image](https://github.com/user-attachments/assets/a0bf6975-fc95-4233-8b8e-3581a66b61b2)
2. Then arrange them in proper order:
![Image](https://github.com/user-attachments/assets/ba45d8db-016c-4843-b28c-950be0823522)
3. Then click on the project name in the menu on the left to reload the project, the ordering is (arbitrarily?) changed:
![Image](https://github.com/user-attachments/assets/55d69265-f877-4cc8-88a3-6fe55a4fb7b6)
4. Rearranging the items to proper order:
![Image](https://github.com/user-attachments/assets/6712d153-1759-4cca-8fa4-c04f88bf8261)
5. Then clicking on the project name once more on the left:
![Image](https://github.com/user-attachments/assets/91e7ce59-df28-462d-be3d-87b599415c39)

etc...

**Comment by SteffenBrinckmann** [comment]
Yes, I can reproduce with the standard example: Move a 9999 into not the first position. 
Issue: items have an order number (0...) and then there are some that have a 9999 as they are at the end in random order. 
Solution: during first move, all items should have an order number in project.py:modelChanged

Code right now: siblingsOld and siblingsNew do not have the 9999 items included, that change is easy
- but these items need to know the current row number, iterate through the model

**Comment by SteffenBrinckmann** [comment]
Fixed in 3.0.14

**Comment by gwinkens** [comment]
Still present in the current version:

![Image](https://github.com/user-attachments/assets/85102514-409b-42c7-ac3d-2a54f96a6edf)
Shifting the items:
![Image](https://github.com/user-attachments/assets/174cd9c3-29dd-49a9-8874-866df0ed887d)
Clicking on the project name on the left:
![Image](https://github.com/user-attachments/assets/40f9a99c-7d62-4ccb-9383-9da14668735f)

**Comment by SteffenBrinckmann** [comment]
@gwinkens I tried to drag-drop the third item into the first position and it worked, also after refresh. 
I have to test/debug it on our computer in your presence:
- in project.py uncomment lines 310
- in fixedStrings.py change "branch"->"comment" line 119
- rerun without debugger
Are you available tomorrow 9:30?

**Comment by gwinkens** [comment]
I am. However, I need to get pasta running again until then (see #408 ).

**Comment by SteffenBrinckmann** [comment]
@gwinkens Fixed it, hopefully.
Can you verify it in the next version

**Comment by gwinkens** [comment]
Still an issue for items within a folder:

![Image](https://github.com/user-attachments/assets/4603fbef-29ea-409c-8990-69e2027c4259)

Moving "XRD..."to the second position:

![Image](https://github.com/user-attachments/assets/66404e10-cf9f-4d8a-84f4-2e33cf44973d)

clicking on the project name again:

![Image](https://github.com/user-attachments/assets/df345281-01f0-407f-be9d-b5ccbc893bd2)
