### ISSUE TITLE
Update of extractors in the current project group

### ISSUE THREAD

**Issue by gwinkens** [PASTA-ELN/pasta-eln#466]
Based on my issues by using a tif-extractor from January: Can we have some method to update the extractors in the current project group?

There is a default Add-On folder in the _site-packages/pasta-eln/_  folder with the most current version of each extractor. Is it possible to copy/paste/overwrite the Add-On folder contents of the current project group based on the extractors provided in the site-packages subfolder?

I imagine the following process for already existing projects:

In the configurations menu:
1. Click on a button "Update Add-Ons"
2. Pasta asks for confirmation that the Add-Ons will be overwritten.
3. Pasta copies the contents of the  _site-packages/pasta-eln/AddOn_ folder and pastes it to the current Add-On folder, overwriting any old files of the same name.

Similarly, for new projects:

In the configurations menu:
1. Create a new project group
2. Enter an Add-On folder path
3. The window opens and asks:
a) Do you want to add the Add-Ons of the last project group?
b) Do you want to add the default Add-Ons?
4. Based on the user response, either (a) the last Add-On folder is copied or (b) the default add-ons from _site-packages/pasta-eln/AddOn_ are copied.

**Comment by gwinkens** [comment]
If this would be implemented, an internal check needs to check if the current Add-On folder is identical to the _site-packages/pasta-eln/AddOn_ folder to prevent weird internal loops to overwrite the folder contents with itself.

**Comment by SteffenBrinckmann** [comment]
The request can be easily solved with the current version by the user: go to the project group configuration and "change" the add-on folder to the same location. You will be asked if you want to copy-over.
BTW: Sorry, the extractor in question was never the default extractor as it includes an additional package (micromechanics). You might have forgotten the source...

**Comment by gwinkens** [comment]
The reply is not what I suggest above:
Currently, the Add Ons of _the last active project group_ are copied. These are **not necessarily** the ones from _site-packages/pasta-eln/AddOn_ . 
Example: I created this project 10 minutes ago. The list of extractors is the one that I keep copying and copying to new project groups from old ones (case1, look at the creation dates):

![Image](https://github.com/user-attachments/assets/55e2ce27-afcb-4c69-8369-9ec942f4f0ef)

however, the site-packages subfolder contains the following extractors (case2):

![Image](https://github.com/user-attachments/assets/545de46c-ffaf-4cba-bbe6-623036848f60)

And I would like to ask the user if case1 (copying from the last active project) or if case2 (copying from the well-maintained source folder) should be applied for a new project group.

**Comment by SteffenBrinckmann** [comment]
@gwinkens the code says that it copies the addons from some random another project-group. Not ideal. Changed it to the default source.
Done

**Comment by gwinkens** [comment]
Is this correction implremented in 3.1.8?
Currently, I still get extractors from a random project (e.g., *.emsa is not a standard extractor) :

![Image](https://github.com/user-attachments/assets/02921147-71c5-46ef-833b-e36edc8636b5)
